#!/bin/bash
# gitnightcrawler - Main orchestrator
# Runs discovery, audits top repos, generates morning review
# Usage: ./nightcrawl.sh [--discover-only] [--audit-only <report.json>]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE=$(date +%Y-%m-%d)
LOG_FILE="$ROOT/logs/nightcrawl-${DATE}.log"
SUMMARY_FILE="$ROOT/reports/morning-review-${DATE}.md"

mkdir -p "$ROOT/logs" "$ROOT/reports" "$ROOT/repos"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "============================================"
echo "  gitnightcrawler - $(date)"
echo "============================================"

MODE="${1:---full}"
DISCOVERY_REPORT=""

# Phase 1: Discovery
if [[ "$MODE" != "--audit-only" ]]; then
    echo ""
    echo "[1/5] Running discovery..."
    python3 "$ROOT/scripts/discover.py"
    DISCOVERY_REPORT="$ROOT/reports/discovery-${DATE}.json"
else
    DISCOVERY_REPORT="${2:-}"
    if [[ -z "$DISCOVERY_REPORT" || ! -f "$DISCOVERY_REPORT" ]]; then
        echo "[error] --audit-only requires a valid discovery report path"
        exit 1
    fi
fi

if [[ "$MODE" == "--discover-only" ]]; then
    echo ""
    echo "[done] Discovery only. Report: $DISCOVERY_REPORT"
    exit 0
fi

# Phase 2: Audit repos
echo ""
echo "[2/5] Auditing repos..."

# Write repo list to temp file to avoid pipe + subshell issues
REPO_LIST=$(mktemp)
python3 -c "
import json
report = json.loads(open('$DISCOVERY_REPORT').read())
for repo in report.get('top_repos', []):
    print(f\"{repo['full_name']}|{repo['url']}|main\")
for repo in report.get('marketing_repos', []):
    print(f\"{repo['full_name']}|{repo['url']}|marketing\")
" > "$REPO_LIST"

echo "Repos to audit:"
cat "$REPO_LIST"
echo ""

while IFS='|' read -r name url category; do
    echo ""
    echo "--- [$category] $name ---"
    bash "$ROOT/scripts/audit.sh" "$name" "$url" "$category" || {
        echo "[warn] Audit failed for $name, continuing..."
    }
done < "$REPO_LIST"
rm -f "$REPO_LIST"

# Phase 3: Generate morning review summary
echo ""
echo "[3/5] Generating morning review..."

cat > "$SUMMARY_FILE" << HEADER
# Morning Review - $DATE

> Generated by gitnightcrawler at $(date)
> Review these findings and decide which PRs to push.

---

HEADER

# Add discovery summary
python3 -c "
import json
r = json.loads(open('$DISCOVERY_REPORT').read())
print('## Discovery Summary')
print(f'- Main candidates scored: {r[\"scored_main\"]}')
print(f'- Marketing candidates scored: {r[\"scored_marketing\"]}')
print()
print('## Top Repos')
print()
for i, repo in enumerate(r.get('top_repos', []), 1):
    m = repo['momentum']
    print(f'### {i}. [{repo[\"full_name\"]}]({repo[\"url\"]})')
    print(f'> {repo[\"description\"]}')
    print(f'> Stars: {repo[\"stars\"]:,} | Issues: {repo[\"open_issues\"]} | Lang: {repo[\"language\"]} | Score: {m[\"momentum_score\"]}')
    print()
print('## Marketing Farm')
print()
for i, repo in enumerate(r.get('marketing_repos', []), 1):
    m = repo['momentum']
    print(f'### {i}. [{repo[\"full_name\"]}]({repo[\"url\"]})')
    print(f'> {repo[\"description\"]}')
    print(f'> Stars: {repo[\"stars\"]:,} | Issues: {repo[\"open_issues\"]} | Lang: {repo[\"language\"]} | Score: {m[\"momentum_score\"]}')
    print()
" >> "$SUMMARY_FILE"

# Append audit reports
echo "## Audit Reports" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

for audit_file in "$ROOT/reports/"audit-*-"${DATE}".md; do
    if [ -f "$audit_file" ]; then
        echo "---" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
        cat "$audit_file" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
    fi
done

# Phase 4: Push reports to GitHub
echo ""
echo "[4/5] Pushing reports to GitHub..."
cd "$ROOT"
git add reports/morning-review-"${DATE}".md reports/discovery-"${DATE}".json reports/audit-*-"${DATE}".md 2>/dev/null || true
git commit -m "chore: nightly report ${DATE}" 2>/dev/null && git push 2>&1 || {
    echo "[warn] Git push failed or nothing to commit"
}
REPORT_URL="https://github.com/GuigsEvt/gitnightcrawler/blob/main/reports/morning-review-${DATE}.md"

# Phase 5: WhatsApp notification
echo ""
echo "[5/5] Sending WhatsApp notification..."
bash "$ROOT/scripts/notify.sh" "$DISCOVERY_REPORT" "$REPORT_URL" || {
    echo "[warn] WhatsApp notification failed"
}

echo "============================================"
echo "  Nightly crawl complete - $(date)"
echo "============================================"
echo ""
echo "Morning review: $SUMMARY_FILE"
echo "GitHub: $REPORT_URL"
echo ""
echo "Reports:"
ls -la "$ROOT/reports/"*"${DATE}"* 2>/dev/null || echo "  (none)"
