#!/bin/bash
# gitnightcrawler - Main orchestrator
# Runs discovery, audits top repos with Trail of Bits skills, generates morning review
# Usage: ./nightcrawl.sh [--discover-only] [--audit-only <report.json>]

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DATE=$(date +%Y-%m-%d)
LOG_FILE="$ROOT/logs/nightcrawl-${DATE}.log"
REPORT_DIR="$ROOT/reports/$DATE"
SUMMARY_FILE="$REPORT_DIR/morning-review.md"

mkdir -p "$ROOT/logs" "$REPORT_DIR" "$ROOT/repos"

exec > >(tee -a "$LOG_FILE") 2>&1

echo "============================================"
echo "  gitnightcrawler - $(date)"
echo "  Trail of Bits skills-powered audit"
echo "============================================"

MODE="${1:---full}"
DISCOVERY_REPORT=""

# Phase 1: Discovery
if [[ "$MODE" != "--audit-only" ]]; then
    echo ""
    echo "[1/5] Running discovery..."
    python3 "$ROOT/scripts/discover.py"
    DISCOVERY_REPORT="$REPORT_DIR/discovery.json"
    # Move discovery report if it was saved in old location
    if [ -f "$ROOT/reports/discovery-${DATE}.json" ] && [ ! -f "$DISCOVERY_REPORT" ]; then
        mv "$ROOT/reports/discovery-${DATE}.json" "$DISCOVERY_REPORT"
    fi
else
    DISCOVERY_REPORT="${2:-}"
    if [[ -z "$DISCOVERY_REPORT" || ! -f "$DISCOVERY_REPORT" ]]; then
        echo "[error] --audit-only requires a valid discovery report path"
        exit 1
    fi
fi

if [[ "$MODE" == "--discover-only" ]]; then
    echo ""
    echo "[done] Discovery only. Report: $DISCOVERY_REPORT"
    exit 0
fi

# Phase 2: Audit repos with Trail of Bits skills
echo ""
echo "[2/5] Auditing repos with Trail of Bits skills..."

REPO_LIST=$(mktemp)
python3 -c "
import json
report = json.loads(open('$DISCOVERY_REPORT').read())
for repo in report.get('top_repos', []):
    print(f\"{repo['full_name']}|{repo['url']}|main\")
for repo in report.get('marketing_repos', []):
    print(f\"{repo['full_name']}|{repo['url']}|marketing\")
" > "$REPO_LIST"

echo "Repos to audit:"
cat "$REPO_LIST"
echo ""

while IFS='|' read -r name url category; do
    echo ""
    echo "--- [$category] $name ---"
    bash "$ROOT/scripts/audit.sh" "$name" "$url" "$category" || {
        echo "[warn] Audit failed for $name, continuing..."
    }
done < "$REPO_LIST"
rm -f "$REPO_LIST"

# Phase 3: Generate morning review summary
echo ""
echo "[3/5] Generating morning review..."

cat > "$SUMMARY_FILE" << HEADER
# Morning Review - $DATE

> Generated by gitnightcrawler at $(date)
> Powered by Trail of Bits security skills
> Review these findings and decide which PRs to push.

---

HEADER

# Add discovery summary
python3 -c "
import json
r = json.loads(open('$DISCOVERY_REPORT').read())
print('## Discovery Summary')
print(f'- Main candidates scored: {r[\"scored_main\"]}')
print(f'- Marketing candidates scored: {r[\"scored_marketing\"]}')
print()
print('## Top Repos')
print()
for i, repo in enumerate(r.get('top_repos', []), 1):
    m = repo['momentum']
    print(f'### {i}. [{repo[\"full_name\"]}]({repo[\"url\"]})')
    print(f'> {repo[\"description\"]}')
    print(f'> Stars: {repo[\"stars\"]:,} | Issues: {repo[\"open_issues\"]} | Lang: {repo[\"language\"]} | Score: {m[\"momentum_score\"]}')
    print()
print('## Marketing Farm')
print()
for i, repo in enumerate(r.get('marketing_repos', []), 1):
    m = repo['momentum']
    print(f'### {i}. [{repo[\"full_name\"]}]({repo[\"url\"]})')
    print(f'> {repo[\"description\"]}')
    print(f'> Stars: {repo[\"stars\"]:,} | Issues: {repo[\"open_issues\"]} | Lang: {repo[\"language\"]} | Score: {m[\"momentum_score\"]}')
    print()
" >> "$SUMMARY_FILE"

# Add security findings summary
echo "## Security Findings Summary" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

python3 -c "
import json, glob, os

findings_dir = '$REPORT_DIR'
findings_files = glob.glob(os.path.join(findings_dir, 'findings-*.json'))

total_critical = 0
total_high = 0
alerts = []

print('| Repo | Risk | Critical | High | Medium | Low | Categories |')
print('|------|------|----------|------|--------|-----|------------|')

for f in sorted(findings_files):
    try:
        data = json.load(open(f))
        total_critical += data.get('critical', 0)
        total_high += data.get('high', 0)
        risk = data.get('risk_level', 'UNKNOWN')
        print(f'| {data[\"repo\"]} | {risk} | {data.get(\"critical\", 0)} | {data.get(\"high\", 0)} | {data.get(\"medium\", 0)} | {data.get(\"low\", 0)} | {data.get(\"categories\", \"general\")} |')
        if data.get('critical', 0) > 0 or data.get('high', 0) > 0:
            alerts.append(data)
    except Exception as e:
        print(f'| (error reading {os.path.basename(f)}) | - | - | - | - | - | - |')

print()
if total_critical > 0 or total_high > 0:
    print(f'**ALERT: {total_critical} critical and {total_high} high severity findings across all repos.**')
    print()
print(f'Total findings: {total_critical} critical, {total_high} high')
" >> "$SUMMARY_FILE"

echo "" >> "$SUMMARY_FILE"

# Append audit reports
echo "## Detailed Audit Reports" >> "$SUMMARY_FILE"
echo "" >> "$SUMMARY_FILE"

for audit_file in "$REPORT_DIR/"audit-*.md; do
    if [ -f "$audit_file" ]; then
        echo "---" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
        cat "$audit_file" >> "$SUMMARY_FILE"
        echo "" >> "$SUMMARY_FILE"
    fi
done

# Also keep a symlink to latest report at root level for backward compat
ln -sf "$DATE/morning-review.md" "$ROOT/reports/morning-review-${DATE}.md" 2>/dev/null || true

# Phase 4: Push reports to GitHub
echo ""
echo "[4/5] Pushing reports to GitHub..."
cd "$ROOT"
git add "reports/$DATE/" "reports/morning-review-${DATE}.md" 2>/dev/null || true
git commit -m "chore: nightly report ${DATE}" 2>/dev/null && git push 2>&1 || {
    echo "[warn] Git push failed or nothing to commit"
}
REPORT_URL="https://github.com/GuigsEvt/gitnightcrawler/blob/main/reports/${DATE}/morning-review.md"

# Phase 5: WhatsApp notification with critical/high alerts
echo ""
echo "[5/5] Sending WhatsApp notification..."
bash "$ROOT/scripts/notify.sh" "$DISCOVERY_REPORT" "$REPORT_URL" || {
    echo "[warn] WhatsApp notification failed"
}

echo "============================================"
echo "  Nightly crawl complete - $(date)"
echo "============================================"
echo ""
echo "Morning review: $SUMMARY_FILE"
echo "GitHub: $REPORT_URL"
echo ""
echo "Reports:"
ls -la "$REPORT_DIR/"* 2>/dev/null || echo "  (none)"
